# Generated by Django 3.1 on 2020-08-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=10)),
                ('hourly_rate', models.IntegerField(default=10, editable=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapi.teamid')),
            ],
        ),
    ]
