# Generated by Django 3.1 on 2020-08-31 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapi.workarr'),
        ),
    ]
