# Generated by Django 3.1 on 2020-09-07 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='team',
            name='Team_leader_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employeeapi.employee'),
            preserve_default=False,
        ),
    ]
