# Generated by Django 3.1 on 2020-09-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0002_auto_20200903_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=10),
        ),
    ]
