# Generated by Django 3.1 on 2020-09-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0003_auto_20200907_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_leader',
            name='TL_salary',
            field=models.FloatField(default=10),
        ),
    ]
