# Generated by Django 3.1 on 2020-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0004_team_leader_tl_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamLeaderId',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Team_Leader',
        ),
    ]
